docker homework
Otus-DevOps-2021-05/panthrashkov_microservices pull request #1
Opened 2021-08-02 19:54 UTC by panthrashkov

# Выполнено ДЗ № 16

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создан docker образ включающий установленную mongodb, ruby и приложение reddit
 - образ размещен в docker hub
 - Контейнер из образа запущен на удаленной машине (docker-machine)
 

## Как запустить проект:
 - docker run --name reddit -d -p 9292:9292 panthrashkov/otus-reddit:1.0

## Как проверить работоспособность:
 - перейти по ссылке http://localhost:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-08-03 08:52 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. К сожалению возникли некоторые проблемы, оставил комметарии к файлу. ДЗ возвращаю на доработку.

2021-08-03 08:52 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
А вот тут видимо и проблема

2021-08-03 08:52 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Попробуйте версию 16.04

2021-08-03 08:52 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +RUN cd /reddit && rm Gemfile.lock && bundle install
Так же попробуйте не удалять Gemfile

2021-08-04 20:11 UTC, panthrashkov commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Да, спасибо, помогло)

2021-08-04 20:12 UTC, panthrashkov commented on docker-monolith/Dockerfile
> +RUN cd /reddit && rm Gemfile.lock && bundle install
Да, удалил удаление)

2021-08-06 13:34 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-08-09 16:02 UTC, merged